extends:
  - _base_/trainer/default.yaml

global:
  project: synth
  name: resnet18_fake
  seed: 0

task:
  _target_: anvil.stock.tasks.classification.SimpleClassificationTask
  backbone:
    _target_: anvil.stock.components.backbones.resnet.ResNet18
  head:
    _target_: anvil.stock.components.heads.linear.LinearHead
    num_classes: 10
  data:
    _target_: anvil.stock.data.classification.cifar.ClassificationSyntheticData
    train_size: 32
    val_size: 16
    batch_size: 8
  optimizer:
    _target_: anvil.stock.components.optim.sgd.SGD
    lr: 0.1
  scheduler:
    _target_: anvil.stock.components.optim.sgd.CosineAnnealing
    t_max: ${trainer.max_epochs}

trainer:
  max_epochs: 1
  accelerator: cpu
  devices: 1
