"""anvil.core.init: scaffold a project folder with a forgeable config YAML."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from omegaconf import OmegaConf

from anvil.core.config.base import resolve_target
from anvil.core.config.errors import AnvilConfigError
from anvil.core.experiment import Experiment, GlobalConfig, Trainer
from anvil.core.runtime.live import dump_experiment
from anvil.core.task import Task

__all__ = ["init_project"]

_DEFAULT_CONFIG_NAME = "config.yaml"

_SKELETON = """\
# Generated by `anvil init`.
# Edit fields, then: anvil forge config.yaml --dry-run

global:
  project: {project}
  name: experiment
  seed: 42
  output_dir: outputs

task:
  _target_: anvil.blueprints.ResNet18Classification
  # Optional overrides (omit _target_ when the blueprint field type is concrete):
  # head:
  #   num_classes: 10
  # data:
  #   _target_: anvil.stock.data.classification.cifar.ClassificationSyntheticData
  #   train_size: 64
  #   val_size: 32
  #   batch_size: 8

trainer:
  max_epochs: 100
  accelerator: auto
  devices: auto
  precision: 32-true
  log_every_n_steps: 50
"""


def init_project(
    directory: str | Path = ".",
    *,
    blueprint: str | None = None,
    force: bool = False,
    filename: str = _DEFAULT_CONFIG_NAME,
) -> Path:
    """Create ``directory`` (if needed) and write a template experiment YAML.

    Args:
        directory: Project folder to scaffold. Defaults to ``.``.
        blueprint: Optional dotted path to a Task blueprint (e.g.
            ``anvil.blueprints.ResNet18Classification``). Defaults to None
            (generic skeleton).
        force: Overwrite an existing config file. Defaults to False.
        filename: Config file name inside ``directory``. Defaults to
            ``config.yaml``.

    Returns:
        Path to the written config file.

    Raises:
        AnvilConfigError: If the path exists and ``force`` is False, or the
            blueprint path is invalid.
    """
    root = Path(directory).expanduser().resolve()
    root.mkdir(parents=True, exist_ok=True)
    out = root / filename
    if out.exists() and not force:
        raise AnvilConfigError(
            f"config already exists: {out}",
            path=str(out),
            hint="pass --force to overwrite, or choose another directory",
        )
    body = (
        _render_blueprint(blueprint, project=root.name)
        if blueprint
        else _SKELETON.format(project=_safe_project_name(root.name))
    )
    out.write_text(body if body.endswith("\n") else body + "\n", encoding="utf-8")
    return out


def _render_blueprint(path: str, *, project: str) -> str:
    target = resolve_target(path)
    if not issubclass(target, Task):
        raise AnvilConfigError(
            "`--blueprint` must name a Task (or Task subclass) Buildable",
            path="_target_",
            value=path,
            hint="example: anvil.blueprints.ResNet18Classification",
        )
    task = target()
    experiment = Experiment(
        global_=GlobalConfig(
            project=_safe_project_name(project),
            name=target.__name__,
            seed=42,
        ),
        task=task,
        trainer=Trainer(),
    )
    dumped = dump_experiment(experiment)
    _strip_nulls(dumped)
    header = (
        f"# Generated by `anvil init --blueprint {path}`.\n"
        f"# Forge with: anvil forge {_DEFAULT_CONFIG_NAME} --dry-run\n"
    )
    return header + OmegaConf.to_yaml(dumped)


def _safe_project_name(name: str) -> str:
    cleaned = "".join(ch if ch.isalnum() or ch in "-_" else "_" for ch in name.strip())
    return cleaned or "project"


def _strip_nulls(node: Any) -> None:
    """Drop ``None`` leaves so the YAML stays editable and compact."""
    if isinstance(node, dict):
        for key in list(node):
            value = node[key]
            if value is None:
                del node[key]
            else:
                _strip_nulls(value)
    elif isinstance(node, list):
        for item in node:
            _strip_nulls(item)
